# Generated by Django 4.2.7 on 2023-11-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("paid", "Paid")],
                default="pending",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[("payment", "Payment"), ("fine", "Fine")],
                default="payment",
                max_length=7,
            ),
        ),
    ]
