# Generated by Django 4.2.7 on 2023-11-28 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0005_borrowing_borrowing_b_user_id_0bdf28_idx_and_more"),
        ("payment", "0002_alter_payment_status_alter_payment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="borrowing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="borrowing.borrowing",
            ),
        ),
    ]
