# Generated by Django 4.2.7 on 2023-11-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("book", "0002_book_annotation"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Borrowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrow_date", models.DateField(auto_now_add=True)),
                ("expected_return_date", models.DateField(auto_now_add=True)),
                ("actual_return_date", models.DateField(auto_now_add=True)),
                (
                    "book",
                    models.ManyToManyField(related_name="borrowing", to="book.book"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowing",
                        to="user.userprofile",
                    ),
                ),
            ],
        ),
    ]
