# Generated by Django 4.2.7 on 2023-11-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={"ordering": ("-borrow_date",)},
        ),
        migrations.AddField(
            model_name="borrowing",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(editable=False),
        ),
    ]
