# Generated by Django 4.2.7 on 2023-11-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0003_alter_borrowing_actual_return_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
