# Generated by Django 4.2.7 on 2023-11-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0004_alter_borrowing_actual_return_date"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="borrowing",
            index=models.Index(
                fields=["user", "is_active"], name="borrowing_b_user_id_0bdf28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="borrowing",
            index=models.Index(
                fields=["expected_return_date"], name="borrowing_b_expecte_9864e4_idx"
            ),
        ),
    ]
