# Generated by Django 4.2.7 on 2023-11-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="annotation",
            field=models.TextField(blank=True),
        ),
    ]
