# Generated by Django 4.2.7 on 2023-11-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_book_annotation"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["title", "author"], name="book_book_title_02eae5_idx"
            ),
        ),
    ]
