# Generated by Django 4.2.7 on 2023-11-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["username"], name="user_userpr_usernam_3ab205_idx"
            ),
        ),
    ]
