# Generated by Django 4.2.7 on 2023-11-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_userprofile_user_userpr_usernam_3ab205_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userprofile",
            name="user_userpr_usernam_3ab205_idx",
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["user", "username"], name="user_userpr_user_id_c5fbce_idx"
            ),
        ),
    ]
