# Generated by Django 4.2.7 on 2023-11-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_remove_userprofile_user_userpr_usernam_3ab205_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
