# Generated by Django 4.2.7 on 2023-12-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_userprofile_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="telebot_chatID",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_num",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
