# Generated by Django 4.2.7 on 2023-12-03 19:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_userprofile_telebot_chatid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="telebot_chatID",
            new_name="telebot_chat_ID",
        ),
    ]
